/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceVisual;

import Poderes.Poder;
import Poderes.TipoDePoderes.AutoModificacao;
import Poderes.TipoDePoderes.LocalAlvo;
import coliseumrpg.Personagem;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javafx.geometry.Dimension2D;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;

/**
 *
 * @author Matheus
 */
public class TelaEmJogo extends javax.swing.JPanel {

    JButton localButtons[][];
    HashMap<JButton, Dimension2D> posicaoBotoes;
    ActionListener mapButtonsDefaulListener = evt -> {
        ControladorTelas.errorDialog("Selecione uma ação no meu lateral primeiro.");
    };
    ActionListener mapButtonsListener = mapButtonsDefaulListener;
    AbstractAction mapsButtonsAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            mapButtonsListener.actionPerformed(e);
        }
    };

    public TelaEmJogo() {
        preInit();
        initComponents();
        postInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void preInit() {
        localButtons = new JButton[20][12];
        posicaoBotoes = new HashMap();

    }

    private void postInit() {
        panelMap.setLayout(new GridLayout(20, 12));
        for (int i = 0; i < localButtons.length; i++) {
            for (int j = 0; j < localButtons[i].length; j++) {
                JButton btn = new JButton();
                Dimension dimension = new Dimension(30, 30);
                posicaoBotoes.put(btn, new Dimension2D(i, j));
                btn.setSize(dimension);
                btn.setMinimumSize(dimension);
                btn.setAction(mapsButtonsAction);
                panelMap.add(btn);
                localButtons[i][j] = btn;
            }
        }
    }

    public void refreshPanel() {

    }

    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelMenuEscolhas = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtacar = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        btnEspecialidade = new javax.swing.JButton();
        panelMenuRotativo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblTurno = new javax.swing.JButton();
        panelSeusPersonagens = new javax.swing.JPanel();
        lblVoce = new javax.swing.JLabel();
        prograssBar1Voce = new javax.swing.JProgressBar();
        lblPersonagem1Voce = new javax.swing.JLabel();
        lblPersonagem2Voce = new javax.swing.JLabel();
        prograssBar2Voce = new javax.swing.JProgressBar();
        panelPersonagensAdversario = new javax.swing.JPanel();
        lblAdversario = new javax.swing.JLabel();
        prograssBar1Adversario = new javax.swing.JProgressBar();
        lblPersonagem2Adversario = new javax.swing.JLabel();
        lblPersonagem1Adversario = new javax.swing.JLabel();
        prograssBar2Adversario = new javax.swing.JProgressBar();
        panelMap = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setPreferredSize(new java.awt.Dimension(800, 550));

        panelMenuEscolhas.setBorder(new javax.swing.border.MatteBorder(null));
        panelMenuEscolhas.setMaximumSize(new java.awt.Dimension(200, 550));
        panelMenuEscolhas.setMinimumSize(new java.awt.Dimension(200, 550));

        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        btnMover.setText("Mover");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });

        btnEspecialidade.setText("Especialidade");
        btnEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialidadeActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout panelMenuRotativoLayout = new javax.swing.GroupLayout(panelMenuRotativo);
        panelMenuRotativo.setLayout(panelMenuRotativoLayout);
        panelMenuRotativoLayout.setHorizontalGroup(
            panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuRotativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuRotativoLayout.setVerticalGroup(
            panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuRotativoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        lblTurno.setText("Turno");

        javax.swing.GroupLayout panelMenuEscolhasLayout = new javax.swing.GroupLayout(panelMenuEscolhas);
        panelMenuEscolhas.setLayout(panelMenuEscolhasLayout);
        panelMenuEscolhasLayout.setHorizontalGroup(
            panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(panelMenuRotativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuEscolhasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtacar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuEscolhasLayout.setVerticalGroup(
            panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuEscolhasLayout.createSequentialGroup()
                .addComponent(panelMenuRotativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSeusPersonagens.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelSeusPersonagens.setMaximumSize(new java.awt.Dimension(290, 150));
        panelSeusPersonagens.setMinimumSize(new java.awt.Dimension(290, 150));
        panelSeusPersonagens.setPreferredSize(new java.awt.Dimension(290, 150));

        lblVoce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVoce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoce.setText("Você");

        lblPersonagem1Voce.setText("NomeClasse");

        lblPersonagem2Voce.setText("NomeClasse");

        javax.swing.GroupLayout panelSeusPersonagensLayout = new javax.swing.GroupLayout(panelSeusPersonagens);
        panelSeusPersonagens.setLayout(panelSeusPersonagensLayout);
        panelSeusPersonagensLayout.setHorizontalGroup(
            panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeusPersonagensLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(lblVoce, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(panelSeusPersonagensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prograssBar1Voce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prograssBar2Voce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSeusPersonagensLayout.createSequentialGroup()
                        .addGroup(panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonagem1Voce)
                            .addComponent(lblPersonagem2Voce))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSeusPersonagensLayout.setVerticalGroup(
            panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeusPersonagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVoce)
                .addGap(8, 8, 8)
                .addComponent(lblPersonagem1Voce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prograssBar1Voce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersonagem2Voce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prograssBar2Voce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPersonagensAdversario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelPersonagensAdversario.setMaximumSize(new java.awt.Dimension(290, 150));
        panelPersonagensAdversario.setMinimumSize(new java.awt.Dimension(290, 150));
        panelPersonagensAdversario.setName(""); // NOI18N
        panelPersonagensAdversario.setPreferredSize(new java.awt.Dimension(290, 150));

        lblAdversario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdversario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdversario.setText("Adversário");

        lblPersonagem2Adversario.setText("NomeClasse");

        lblPersonagem1Adversario.setText("NomeClasse");

        javax.swing.GroupLayout panelPersonagensAdversarioLayout = new javax.swing.GroupLayout(panelPersonagensAdversario);
        panelPersonagensAdversario.setLayout(panelPersonagensAdversarioLayout);
        panelPersonagensAdversarioLayout.setHorizontalGroup(
            panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblAdversario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prograssBar1Adversario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prograssBar2Adversario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                        .addGroup(panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonagem1Adversario)
                            .addComponent(lblPersonagem2Adversario))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPersonagensAdversarioLayout.setVerticalGroup(
            panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdversario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonagem1Adversario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prograssBar1Adversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersonagem2Adversario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prograssBar2Adversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelMap.setBorder(new javax.swing.border.MatteBorder(null));
        panelMap.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeusPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPersonagensAdversario, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addComponent(panelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenuEscolhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelMenuEscolhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPersonagensAdversario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSeusPersonagens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
    }//GEN-END:initComponents

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        if (mapButtonsListener == mapButtonsDefaulListener) {
            mapButtonsListener = event -> {
                ControladorTelas.getInstance().mover(posicaoBotoes.get((JButton) event.getSource()));
                mapButtonsListener = mapButtonsDefaulListener;
            };
        } else {
            mapButtonsListener = mapButtonsDefaulListener;
        }
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        if (mapButtonsListener == mapButtonsDefaulListener) {
            mapButtonsListener = event -> {
                ControladorTelas.getInstance().atacar(posicaoBotoes.get((JButton) event.getSource()));
                mapButtonsListener = mapButtonsDefaulListener;
            };
        } else {
            mapButtonsListener = mapButtonsDefaulListener;
        }
    }//GEN-LAST:event_btnAtacarActionPerformed

    private void btnEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialidadeActionPerformed
        Poder[] poderes = ControladorTelas.getInstance().getPoderesPersonagemDoTurno();
        panelMenuRotativo.removeAll();
        for (Poder poder : poderes) {
            JButton btn = new JButton(poder.getNome());
            btn.setToolTipText(poder.getDescricao());
            if (poder instanceof LocalAlvo) {
                ActionListener poderLocalAlvoListener = poderLocalAlvoEvent -> {
                    if (mapButtonsListener == mapButtonsDefaulListener) {
                        mapButtonsListener = mapButtonEvent -> {
                            ControladorTelas.getInstance().usarPoderLocalAlvo((LocalAlvo) poder, posicaoBotoes.get((JButton) mapButtonEvent.getSource()));
                            mapButtonsListener = mapButtonsDefaulListener;
                        };
                    } else {
                        mapButtonsListener = mapButtonsDefaulListener;
                    }
                };
                btn.addActionListener(poderLocalAlvoListener);;
            } else if (poder instanceof AutoModificacao) {
                ActionListener poderAutoModificacaoListener = poderLocalAlvoEvent -> {
                    ControladorTelas.getInstance().usarPoderAutoModificacao((AutoModificacao) poder);
                };
                btn.addActionListener(poderAutoModificacaoListener);
            } else {
                throw new RuntimeException("O poder " + poder.getNome() + " não tem interface definida em TelaEmJogo, caso ja tenha essa interface criada basta adiciona-la na lista com o instanceof e implementar a forma de usa-lo.");
            }
            panelMenuRotativo.add(btn);
        }
    }//GEN-LAST:event_btnEspecialidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnEspecialidade;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdversario;
    private javax.swing.JLabel lblPersonagem1Adversario;
    private javax.swing.JLabel lblPersonagem1Voce;
    private javax.swing.JLabel lblPersonagem2Adversario;
    private javax.swing.JLabel lblPersonagem2Voce;
    private javax.swing.JButton lblTurno;
    private javax.swing.JLabel lblVoce;
    private javax.swing.JPanel panelMap;
    private javax.swing.JPanel panelMenuEscolhas;
    private javax.swing.JPanel panelMenuRotativo;
    private javax.swing.JPanel panelPersonagensAdversario;
    private javax.swing.JPanel panelSeusPersonagens;
    private javax.swing.JProgressBar prograssBar1Adversario;
    private javax.swing.JProgressBar prograssBar1Voce;
    private javax.swing.JProgressBar prograssBar2Adversario;
    private javax.swing.JProgressBar prograssBar2Voce;
    // End of variables declaration//GEN-END:variables

}
