/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceVisual;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author Matheus
 */
public class TelaEmJogo extends javax.swing.JPanel {

    /**
     * Creates new form TelaOnGame
     */
    JButton localButtons[][];

    public TelaEmJogo() {
        preInit();
        initComponents();
        postInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void preInit() {
        localButtons = new JButton[20][13];

    }

    private void postInit() {
        panelMap.setLayout(new GridLayout(20, 12));
        for (int i = 0; i < localButtons.length; i++) {
            for (int j = 0; j < localButtons[i].length; i++) {
                JButton btn = new JButton();
                Dimension dimension = new Dimension(30, 30);
                btn.setSize(dimension);
                btn.setMinimumSize(dimension);
                panelMap.add(btn);
                localButtons[i][j] = btn;
            }
        }
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelMenuEscolhas = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtacar = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        btnEspecialidade = new javax.swing.JButton();
        panelMenuRotativo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelSeusPersonagens = new javax.swing.JPanel();
        lblVoce = new javax.swing.JLabel();
        panelPersonagensAdversario = new javax.swing.JPanel();
        lblAdversario = new javax.swing.JLabel();
        panelMap = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));

        panelMenuEscolhas.setBorder(new javax.swing.border.MatteBorder(null));
        panelMenuEscolhas.setMaximumSize(new java.awt.Dimension(200, 550));
        panelMenuEscolhas.setMinimumSize(new java.awt.Dimension(200, 550));

        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        btnMover.setText("Mover");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });

        btnEspecialidade.setText("Especialidade");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout panelMenuRotativoLayout = new javax.swing.GroupLayout(panelMenuRotativo);
        panelMenuRotativo.setLayout(panelMenuRotativoLayout);
        panelMenuRotativoLayout.setHorizontalGroup(
            panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuRotativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuRotativoLayout.setVerticalGroup(
            panelMenuRotativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuRotativoLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout panelMenuEscolhasLayout = new javax.swing.GroupLayout(panelMenuEscolhas);
        panelMenuEscolhas.setLayout(panelMenuEscolhasLayout);
        panelMenuEscolhasLayout.setHorizontalGroup(
            panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuEscolhasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(panelMenuRotativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuEscolhasLayout.setVerticalGroup(
            panelMenuEscolhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuEscolhasLayout.createSequentialGroup()
                .addComponent(panelMenuRotativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelSeusPersonagens.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelSeusPersonagens.setMaximumSize(new java.awt.Dimension(290, 150));
        panelSeusPersonagens.setMinimumSize(new java.awt.Dimension(290, 150));
        panelSeusPersonagens.setPreferredSize(new java.awt.Dimension(290, 150));

        lblVoce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVoce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoce.setText("Você");

        javax.swing.GroupLayout panelSeusPersonagensLayout = new javax.swing.GroupLayout(panelSeusPersonagens);
        panelSeusPersonagens.setLayout(panelSeusPersonagensLayout);
        panelSeusPersonagensLayout.setHorizontalGroup(
            panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeusPersonagensLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(lblVoce, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        panelSeusPersonagensLayout.setVerticalGroup(
            panelSeusPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeusPersonagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVoce)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPersonagensAdversario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelPersonagensAdversario.setMaximumSize(new java.awt.Dimension(290, 150));
        panelPersonagensAdversario.setMinimumSize(new java.awt.Dimension(290, 150));
        panelPersonagensAdversario.setName(""); // NOI18N
        panelPersonagensAdversario.setPreferredSize(new java.awt.Dimension(290, 150));

        lblAdversario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdversario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdversario.setText("Adversário");

        javax.swing.GroupLayout panelPersonagensAdversarioLayout = new javax.swing.GroupLayout(panelPersonagensAdversario);
        panelPersonagensAdversario.setLayout(panelPersonagensAdversarioLayout);
        panelPersonagensAdversarioLayout.setHorizontalGroup(
            panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblAdversario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelPersonagensAdversarioLayout.setVerticalGroup(
            panelPersonagensAdversarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagensAdversarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdversario)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        panelMap.setBorder(new javax.swing.border.MatteBorder(null));
        panelMap.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeusPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPersonagensAdversario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenuEscolhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelMenuEscolhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPersonagensAdversario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSeusPersonagens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
    }//GEN-END:initComponents

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtacarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnEspecialidade;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdversario;
    private javax.swing.JLabel lblVoce;
    private javax.swing.JPanel panelMap;
    private javax.swing.JPanel panelMenuEscolhas;
    private javax.swing.JPanel panelMenuRotativo;
    private javax.swing.JPanel panelPersonagensAdversario;
    private javax.swing.JPanel panelSeusPersonagens;
    // End of variables declaration//GEN-END:variables

}
